In [1]:
from numpy import *

In [8]:
import numpy as np

In [2]:
random.rand(4,4)

array([[0.96491501, 0.32745284, 0.98899387, 0.64538608],
       [0.38374451, 0.1796318 , 0.44789156, 0.85640674],
       [0.91141741, 0.79414219, 0.36300362, 0.33524184],
       [0.25795891, 0.24843603, 0.30360006, 0.23397741]])

In [3]:
matrix = mat(random.rand(4,4))

In [4]:
matrix

matrix([[0.10928237, 0.24521024, 0.53277851, 0.38818301],
        [0.39222615, 0.83599287, 0.75378632, 0.31770123],
        [0.42305357, 0.89078805, 0.17038132, 0.36872933],
        [0.8062474 , 0.22660006, 0.3678151 , 0.23311173]])

In [5]:
matrix.I

matrix([[-0.71074258, -0.19583509,  0.01752138,  1.42272806],
        [-1.02349538,  0.88909634,  0.74398078, -0.68418274],
        [ 0.1479279 ,  1.556125  , -1.50423184,  0.01221936],
        [ 3.21969367, -2.64226959,  1.58965205,  0.01488809]])

In [6]:
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
a=np.array([[1,2,3],[3,5,6]])
print(a)

[[1 2 3]
 [3 5 6]]


In [17]:
a=np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [18]:
a=np.array([[1,2,3],[3,5,6]])
print(a.shape)

(2, 3)


In [20]:
a = np.ones([2,2],dtype=int)
print(a)

[[1 1]
 [1 1]]


In [21]:
x=[1,2,3]  # list
a = np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [22]:
x=(1,2,3)  #tuple
a = np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [25]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [26]:
a = np.arange(3,10,1)
print(a)

[3 4 5 6 7 8 9]


In [27]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [30]:
a = np.linspace(10,20,3) # eq spacing 
print(a)

[10. 15. 20.]


In [32]:
a = np.linspace(10,20,3, endpoint=False) # eq spacing 
print(a)

[10.         13.33333333 16.66666667]


In [34]:
a = np.linspace(10,20,3,retstep=True) # eq spacing 
print(a)

(array([10., 15., 20.]), 5.0)


In [45]:
a= np.arange(10)
print(a)
s = slice(2,7,2)#(start,stop,step)
print(s)
print (a[s])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]


In [47]:
a= np.arange(10)
print(a)
print(a[2:])
print(a[:2])
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[0 1]
[2 3 4]


In [51]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[...,1]) #rows
print(a[1,...])#columns
print(a[...,1:]) # col onwards

[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]


In [54]:
a = np.array([1,2,3])
b = np.array([10,10,10])
c = a+b #*,-,/
print(c)

[0.1 0.2 0.3]


In [61]:
a = np.arange(0,60,3)
a = a.reshape(5,4)
b= a.T

print(a)
print(b)
c=b.copy(order='C')#sorted in c style order
f=b.copy(order='F')#sorted in f style order
for x in np.nditer(a):#a,c,f
    #print(x)
    pass

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [36 39 42 45]
 [48 51 54 57]]
[[ 0 12 24 36 48]
 [ 3 15 27 39 51]
 [ 6 18 30 42 54]
 [ 9 21 33 45 57]]


In [64]:
a = np.arange(0,60,3)
a = a.reshape(5,4)
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=2*x
print(a)

[[  0   6  12  18]
 [ 24  30  36  42]
 [ 48  54  60  66]
 [ 72  78  84  90]
 [ 96 102 108 114]]
