In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [8]:
a.size

5

In [9]:
a.shape

(5,)

In [10]:
a.tolist

<function ndarray.tolist>

In [11]:
p=a.tolist

In [12]:
p

<function ndarray.tolist>

In [13]:
a.T

array([1, 2, 3, 4, 5])

In [14]:
np.append(a,10)

array([ 1,  2,  3,  4,  5, 10])

In [16]:
np.insert(a,2,15)

array([ 1,  2, 15,  3,  4,  5])

In [17]:
np.delete(a,2)

array([1, 2, 4, 5])

In [18]:
np.delete(a,3)

array([1, 2, 3, 5])

In [19]:
np.delete(a,4)

array([1, 2, 3, 4])

In [20]:
a[:2]

array([1, 2])

In [21]:
a[2:]

array([3, 4, 5])

In [22]:
a

array([1, 2, 3, 4, 5])

In [23]:
np.add(a,5)

array([ 6,  7,  8,  9, 10])

In [24]:
np.subtract(a,5)

array([-4, -3, -2, -1,  0])

In [25]:
a

array([1, 2, 3, 4, 5])

In [26]:
np.add(a,a)

array([ 2,  4,  6,  8, 10])

In [27]:
a.sum()

15