In [5]:
import numpy as np
from sklearn.cluster import MeanShift
from sklearn.datasets.samples_generator import make_blobs
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import style
style.use('ggplot')

In [6]:
centers=[[0,0,0],[50,30,20],[100,100,100]]

In [7]:
X,Z=make_blobs(n_samples=10,centers=centers,cluster_std=9)

In [8]:
print(X)
print(Z)

[[ 58.58583928  29.03898846  26.88955104]
 [ 82.41903655  94.81926431 110.91949472]
 [ 51.71663736  16.2676303   21.74402024]
 [  3.69112274  10.31890071  -0.55221162]
 [ 77.03402994 105.08667517  91.76420899]
 [  4.12501445   3.83409677   1.72464877]
 [  1.19692702  -4.17062257   7.08469871]
 [-18.4341903   -8.162415    16.91264166]
 [ 93.05766185  96.38863788 101.16770783]
 [ 30.11855488  23.54594883  14.26971556]]
[1 2 1 0 2 0 0 0 2 1]
